#---
#
#backend_server_name: "<your-production-server-backend-cname>"
#
#frontend_server_name: "<your-production-server-frontend-cname>"
#
#database_password: "<your-production-database-password>"
#
#firewalld_backend_ip_addresses:
# - <your-production-backend-ip-address>
#
#ssl_provider: 'certbot'
#ssl_certbot_email: '<your-certbot-notification-email>'
