---

- import_tasks: selinux.yml

- import_tasks: dnf_automatic.yml

- name: install epel-release
  yum:
    name: epel-release

- import_tasks: login_info.yml

- name: install useful packages
  dnf:
    name:
      - atop
      - htop
      - lsof
      - nano
      - net-tools
      - nmap
      - vim-enhanced
    state: present
