---

- name: ensure SELinux and python requirements are installed
  yum:
    name:
      - selinux-policy
      - policycoreutils-python
      - libsemanage-python
    state: present

- name: enable SELinux
  selinux:
    policy: targeted
    state: enforcing
