---

- name: ensure SELinux and python requirements are installed
  dnf:
    name:
      - selinux-policy
      - python3-policycoreutils
      - python3-libsemanage
    state: present

- name: enable SELinux
  selinux:
    policy: targeted
    state: enforcing
