---

- name: ensure SELinux is installed
  yum:
    name: selinux-policy
    state: present

- name: enable SELinux
  selinux:
    policy: targeted
    state: enforcing

- name: install libsemanage-python
  yum:
    name: libsemanage-python
    state: present
