---

backend_app_root: "/opt/{{ cookiecutter.project_slug }}_backend"
backend_app_user: "{{ cookiecutter.project_slug }}"
backend_app_group: "{{ cookiecutter.project_slug }}"
{% raw %}backend_app_systemd_pid_file: "/run/{{ backend_app_systemd_runtime_dir }}/gunicorn.pid"{% endraw %}
backend_app_systemd_unit_name: "{{ cookiecutter.project_slug }}"
backend_app_wsgi: "{{ cookiecutter.project_slug }}.wsgi"
