---

backend_app_dir: "/opt/{{ cookiecutter.project_slug }}"
backend_app_user: "{{ cookiecutter.backend_user }}"
backend_app_group: "{{ cookiecutter.backend_group }}"
backend_app_virtualenv_dir: "/home/{{ cookiecutter.backend_user }}/{{ cookiecutter.project_slug }}_virtualenv"
