---

- hosts: all
  become: yes
  pre_tasks:
    - name: check connectivity to all hosts
      ping:
  roles:
    - base
    - firewalld

- hosts: database
  become: yes
  roles:
    - postgresql
  vars_files:
    - vars/postgresql.yml

- hosts: backend
  become: yes
  roles:
    - backend_app
    - nginxinc.nginx
  vars_files:
    - vars/nginx_backend.yml
