---
{% raw %}
- hosts: all
  become: yes
  pre_tasks:
    - name: check connectivity to all hosts
      ping:
  roles:
    - base
    - firewalld

- hosts: database
  become: yes
  roles:
    - postgresql
  vars_files:
    - vars/shared.yml
    - vars/postgresql.yml

- hosts: backend
  become: yes
  roles:
    - backend_app
    - geerlingguy.nginx
  tasks:
    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
  vars_files:
    - vars/shared.yml
    - vars/backend_app.yml
    - vars/postgresql.yml
    - vars/nginx_backend.yml
{% endraw %}