---
{% raw %}
- hosts: all
  become: true
  pre_tasks:
    - name: check connectivity to all hosts
      ping:

    - name: "Set release version fact"
      set_fact:
        release_version: "{{ lookup('pipe','date \"+%Y-%m-%d-%H-%M-%S-%Z\"') }}"
      delegate_to: localhost
      run_once: true

    - name: "Set release version facts"
      set_fact:
        backend_app_release_version: "{{ release_version }}"
  roles:
    - base
    - firewalld

- hosts: database
  become: true
  roles:
    - postgresql
  vars_files:
    - vars/shared.yml
    - vars/postgresql.yml

- hosts: backend
  become: true
  roles:
    - ssl
    - nginx
    - backend_app
  vars_files:
    - vars/shared.yml
    - vars/backend.yml

- hosts: localhost
  become: true
  roles:
    - yarn
  vars:
    ansible_python_interpreter: "/usr/bin/python"

- hosts: frontend
  become: true
  roles:
    - ssl
    - nginx
  vars_files:
    - vars/shared.yml
    - vars/frontend.yml
{% endraw %}