---
{% raw %}
- hosts: all
  become: yes
  pre_tasks:
    - name: check connectivity to all hosts
      ping:
  roles:
    - base
    - firewalld

- hosts: database
  become: yes
  roles:
    - postgresql
  vars_files:
    - vars/shared.yml
    - vars/postgresql.yml

- hosts: backend
  become: yes
  pre_tasks:
    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
  roles:
    - backend_app
    - ssl
    - geerlingguy.nginx
  vars_files:
    - vars/shared.yml
    - vars/backend.yml
{% endraw %}