---

- hosts: all
  become: yes
  pre_tasks:
    - name: check connectivity to all hosts
      ping:
  roles:
    - base

- hosts: database
  become: yes
  roles:
    - postgresql

- hosts: webserver
  become: yes
  roles:
    - backend_app
