---

- src: geerlingguy.postgresql
  version: "2.0.1"

- src: geerlingguy.nginx
  version: "2.7.0"

- src: geerlingguy.nodejs
  version: "5.1.0"

- src: tmiller02.yarn
  version: "0.1.0"

- src: tmiller02.neofetch
  version: "0.1.0"

- src: tmiller02.geckodriver
  version: "0.1.0"
