---
{% raw %}
- assert:
    that:
      - ssl_provider is defined
      - ssl_provider in ['selfsigned']

- name: install packages required for interacting with OpenSSL
  yum:
    name: python2-cryptography
    state: present

- import_tasks: self_signed.yml
  when: ssl_provider == 'selfsigned'
{% endraw %}