---

deploy_check_display_confirmation_prompts: false

base_show_production_login_warning: false
base_install_updates_automatically: true

backend_server_name: "{{ cookiecutter.backend_app_dev_hostname }}"

frontend_server_name: "{{ cookiecutter.frontend_app_dev_hostname }}"

database_password: "$DATABASE PASSWORD$"

firewalld_backend_ip_addresses:
  - 172.17.177.21
{% raw %}
firewalld_additional_rules:
  # Ensure the django dev server is accessible from any address
  - port: "8000/tcp"
    state: "enabled"
    zone: "public"
    when: "{{ 'backend' in group_names }}"
  # Ensure the postgres server is accessible from any address. Don't set this
  # in a production environment!
  - port: "5432/tcp"
    state: "enabled"
    zone: "public"
    when: "{{ 'database' in group_names }}"
{% endraw %}
ssl_provider: 'selfsigned'
