---
{% raw %}
- name: run database migrations
  become: yes
  become_user: "{{ backend_app_user }}"
  run_once: yes
  django_manage:
    command: "migrate --noinput"
    app_path: "{{ backend_app_dir }}"
    virtualenv: "{{ backend_app_virtualenv_dir }}"

- name: run collect static files
  become: yes
  become_user: "{{ backend_app_user }}"
  django_manage:
    command: "collectstatic --clear --noinput"
    app_path: "{{ backend_app_dir }}"
    virtualenv: "{{ backend_app_virtualenv_dir }}"

{% endraw %}
