---
{% raw %}
- include_tasks: users.yml

- include_tasks: virtualenv.yml

- name: synchronize backend_app
  synchronize:
    src: "{{ playbook_dir }}/../backend_app/"
    dest: "{{ backend_app_dir }}"
    delete: yes
    rsync_opts:
      - "--exclude=__pycache__"
      - "--delete-excluded"
  when: backend_app_rsync

- name: template settings
  template:
    src: settings.env.j2
    dest: "{{ backend_app_settings_file }}"
    owner: "{{ backend_app_user }}"
    group: "{{ backend_app_group }}"
    mode: "u=rw,g=,o="

- include_tasks: systemd.yml
{% endraw %}