---
{% raw %}
- include_tasks: users.yml

- name: ensure backend app root folder exists with correct ownership
  file:
    path: "{{ backend_app_root }}"
    state: directory
    owner: "{{ backend_app_user }}"
    group: "{{ backend_app_group }}"

- import_tasks: run_deploy.yml
  when: not backend_app_vagrant_mount | bool

- import_tasks: vagrant_mount.yml
  when: backend_app_vagrant_mount | bool

- import_tasks: virtualenv.yml

- name: template settings into the new release path
  template:
    src: settings.env.j2
    dest: "{{ deploy_helper.new_release_path }}/settings.env"
    owner: "{{ backend_app_user }}"
    group: "{{ backend_app_group }}"
    mode: "u=rw,g=,o="

- name: add gunicorn config to the new release path
  template:
    src: gunicorn.cfg.j2
    dest: "{{ deploy_helper.new_release_path }}/gunicorn.cfg"
    owner: "{{ backend_app_user }}"
    group: "{{ backend_app_group }}"

- name: finalize the deploy, removing the unfinished file and switching the 'current' symlink
  become: yes
  become_user: "{{ backend_app_user }}"
  deploy_helper:
    path: "{{ backend_app_root }}"
    release: '{{ deploy_helper.new_release }}'
    state: finalize
    clean: yes
    keep_releases: 10
  when: not backend_app_vagrant_mount | bool

- name: ensure static directory exists
  file:
    path: "{{ backend_app_static_root }}"
    state: directory
    owner: "{{ backend_app_user }}"
    group: "{{ backend_app_group }}"
    mode: "u=rwx,g=rx,o=rx"

- import_tasks: django_management.yml

- import_tasks: systemd.yml
{% endraw %}