---
{% raw %}
- include_tasks: users.yml

- include_tasks: virtualenv.yml

# WARNING - this task deletes the destination folder contents when syncing.
#
# Any files which aren't managed via ansible (e.g. media files) should never
# be written to the 'backend_app' folder on the destination host if this task
# is being run, since this will cause those files to be deleted.
- name: synchronize backend_app
  synchronize:
    src: "{{ playbook_dir }}/../backend_app/"
    dest: "{{ backend_app_dir }}"
    delete: yes
    rsync_opts:
      - "--exclude=__pycache__"
      - "--delete-excluded"
  when: backend_app_rsync

- name: template settings
  template:
    src: settings.env.j2
    dest: "{{ backend_app_dir }}/settings.env"
    owner: "{{ backend_app_user }}"
    group: "{{ backend_app_group }}"
    mode: "u=rw,g=,o="

- name: ensure static directory exists
  file:
    path: "{{ backend_app_static_root }}"
    state: directory
    owner: "{{ backend_app_user }}"
    group: "{{ backend_app_group }}"
    mode: "u=rwx,g=rx,o=rx"

- include_tasks: django_management.yml

- include_tasks: systemd.yml
{% endraw %}