---
{% raw %}
- name: install epel-release
  yum:
    name: epel-release

- name: install python packages
  yum:
    name:
      - python2-pip
      - python36
      - python36-pip

- name: set up virtualenv in new release path
  become: true
  become_user: "{{ backend_app_user }}"
  pip:
    virtualenv: "{{ deploy_helper.new_release_path }}/venv"
    virtualenv_command: /usr/bin/python3.6 -m venv
    name:
      - pip-tools==4.0.0

- name: install requirements using pip-sync
  become: true
  become_user: "{{ backend_app_user }}"
  command: "venv/bin/pip-sync"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
{% endraw %}