---
{% raw %}
- name: set up virtualenv in new release path
  become: true
  become_user: "{{ backend_app_user }}"
  pip:
    virtualenv: "{{ backend_app_deploy_helper.new_release_path }}/venv"
    virtualenv_command: /usr/bin/python3.6 -m venv
    name:
      - pip-tools==4.2.0

- name: install requirements using pip-sync
  become: true
  become_user: "{{ backend_app_user }}"
  command: "venv/bin/pip-sync"
  args:
    chdir: "{{ backend_app_deploy_helper.new_release_path }}"
{% endraw %}
