---
{% raw %}
ssl_private_key_dest: "/etc/pki/tls/private/{{ ssl_private_key_name }}"
ssl_certificate_dest: "/etc/pki/tls/certs/{{ ssl_certificate_name }}"
ssl_csr_path: "/etc/pki/tls/csr/{{ (ssl_certificate_name | splitext)[0] }}.csr"
{% endraw %}