---
{% raw %}
- name: ensure firewalld is installed
  yum:
    name: firewalld
    state: present

- name: start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: expose http and https in firewalld on 'backend' hosts to the 'public' zone
  firewalld:
    zone: public
    service: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
    - http
    - https
  when: "'backend' in group_names"

- block:
  - name: define the 'backend' firewalld zone
    firewalld:
      zone: backend
      state: present
      permanent: yes

  - name: reload firewalld
    command: "firewall-cmd --reload"

  - name: add entries in firewalld_backend_ip_addresses to the 'backend' firewalld zone
    firewalld:
      zone: backend
      source: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items: "{{ firewalld_backend_ip_addresses }}"

  - name: expose port 5432/tcp for postgres to the 'backend' firewalld zone
    firewalld:
      zone: backend
      port: "5432/tcp"
      immediate: yes
      permanent: yes
      state: enabled

  when: "'database' in group_names"

- name: apply additional firewalld rules
  firewalld:
    service: "{{ item.service | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    immediate: yes
    permanent: yes
    state: "{{ item.state }}"
    zone: "{{ item.zone | default(omit) }}"
  loop: "{{ firewalld_additional_rules }}"
{% endraw %}